"""add foreign key to Review

Revision ID: 1d0d148728b0
Revises: 80406c264a98
Create Date: 2024-07-01 22:12:08.819594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0d148728b0'
down_revision = '80406c264a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_onboardings_employee_id_employees', 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('employee_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_onboardings_employee_id_employees', 'onboardings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
